import test from 'node:test';
import assert from 'node:assert/strict';
import { createArtifact, ReleaseStore } from '../src/index.js';
import { SigningVault } from '../src/cloud.js';
import { SecretVault, DeploymentOrchestrator, createOtaManifest, signOtaManifest, verifyOtaManifest, UpdateClient } from '../src/deployment.js';

function release(store,version='1.0.0',strategy='canary'){const artifact=createArtifact({app:'proof',version,target:'web',files:[{path:'app.js',content:version}]});store.putArtifact(artifact);return store.createRelease({artifactDigest:artifact.digest,environment:{name:'prod',replicas:3,strategy},strategy});}

test('health-gated canary rollout promotes only after all phases are healthy', async()=>{const store=new ReleaseStore();const candidate=release(store);const live=new Set();const audit=[];const deployer=new DeploymentOrchestrator({store,deployReplica:async(_r,{index})=>{const id=`r${index}`;live.add(id);return id;},removeReplica:async(id)=>live.delete(id),healthCheck:async()=>true,audit:async(e)=>audit.push(e)});const result=await deployer.rollout(candidate,{replicas:3});assert.equal(result.ok,true);assert.equal(live.size,3);assert.equal(store.channel('prod').id,candidate.id);assert.deepEqual(result.phases.map(p=>p.deployed),[1,3]);assert.ok(audit.some(e=>e.type==='rollout.phase'));});

test('failed health gate removes new replicas and records rollback outcome',async()=>{const store=new ReleaseStore();const candidate=release(store,'2.0.0');const live=[];const deployer=new DeploymentOrchestrator({store,deployReplica:async(_r,{index})=>{const id=`bad${index}`;live.push(id);return id;},removeReplica:async(id)=>{live.splice(live.indexOf(id),1);},healthCheck:async()=>false});const result=await deployer.rollout(candidate,{replicas:3});assert.equal(result.ok,false);assert.equal(result.rolledBack,true);assert.equal(live.length,0);assert.equal(store.history().find(r=>r.id===candidate.id).status,'unhealthy');});

test('OTA manifests are signed tamper-evident runtime/platform gated and replay protected',()=>{const vault=new SigningVault();vault.create('ota');const manifest=createOtaManifest({app:'proof',runtimeVersion:'1',artifactDigest:'abc',assets:[{path:'bundle',digest:'def'}],eligibility:{platforms:['android']},sequence:7});const signed=signOtaManifest(manifest,vault,'ota');assert.equal(verifyOtaManifest(signed,vault),true);const client=new UpdateClient({runtimeVersion:'1',platform:'android',appVersion:'1.0.0',verify:(entry)=>verifyOtaManifest(entry,vault)});assert.deepEqual(client.accept(signed),{accepted:true,artifactDigest:'abc',assets:[{path:'bundle',digest:'def'}]});assert.equal(client.accept(signed).reason,'replay');const tampered=structuredClone(signed);tampered.manifest.artifactDigest='evil';assert.equal(client.accept(tampered).reason,'signature');});

test('credential vault decrypts only inside lease and zeroizes deleted ciphertext/key state',async()=>{const vault=new SecretVault(Buffer.alloc(32,7));vault.put('android-keystore','super-secret');let observed;await vault.withSecret('android-keystore',async(secret)=>{observed=secret.toString('utf8');assert.equal(secret.toString(),'super-secret');});assert.equal(observed,'super-secret');assert.equal(vault.delete('android-keystore'),true);await assert.rejects(vault.withSecret('android-keystore',async()=>{}),/unknown credential/);vault.close();});
